### ISSUE TITLE
Order milestones by sequence then dates 

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/deprecated-labs-zap-api#100]
Since the sequence of milestones is explicitly set in the CRM, and the dates can be [anything], it's common for milestones of the same sequence to be out of order. 

<img src="https://user-images.githubusercontent.com/409279/53258444-a1dd2900-369a-11e9-8774-d9324458d9fb.png" width=500 />

Currently, milestones are only ordered by `dcp_milestonesequence`: 

https://github.com/NYCPlanning/labs-zap-api/blob/dd0e0c70034cd997d7a01983ef2d4e08fe6d9e5a/queries/projects/show.sql#L160

We should be able to additionally sort those groups of matching sequence into the right order using `dcp_actualstartdate`. I think this is as simple as changing that one line to… 

```
ORDER BY mm.dcp_milestonesequence ASC, mm.dcp_actualstartdate
```

**Comment by SomeCityBureaucrat** [comment]
This came to us via an issue (https://github.com/NYCPlanning/dcp-zap-data-feedback/issues/153) submitted by Aline in the Brooklyn office.  Thanks all.

**Comment by ghost** [comment]
@hannahkates  @andycochran  didn't yall do this in your other change? if so, should close :)

**Comment by hannahkates** [comment]
Closing, this has been implemented.
