### ISSUE TITLE
Frontend/Backend parity for a Project detail

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/deprecated-labs-zap-api#149]
See PR for attributes expected by the front end: https://github.com/NYCPlanning/labs-zap-search/pull/557/files

**Comment by allthesignals** [comment]
@julialucyhogan and I talked and she thinks it's best to keep the `/projects/:id` endpoint sourced through the CRM endpoint, which is necessary anyway to implement write functionality.

Project_s_ _queries_, on the other hand, should still be sourced through the Skyvia ETL database. We will need to think more about the naming for this, but something along the lines of "ReadOnlyProjects" or "ProjectFragments" should do. These will be separate types of objects on the backend.

**Comment by allthesignals** [comment]
@godfreyyeung and I discovered this this weekend: we'll need to have the API return actions properly as side-loaded JSON:API resources rather than a POJO.

**Comment by allthesignals** [comment]
@hannahkates followed up with Bujji on getting production credentials — it appears there's one more step (adding some user record to the organization).

**Comment by allthesignals** [comment]
This has evolved quite a bit but we should be back to square 1 w/r/t api/client parity — there were some changes salvaged from the CRM feature branch, like side-loading actions and milestones as separate resources. This should be considered closed for now unless @hannahkates finds any discrepancy between production and staging
