### ISSUE TITLE
Rename Project Model attributes from CRM-style attribute names to Ember Data style, to match other models

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/deprecated-labs-zap-api#181]
1. remove `dcp_` prefix from attribute names, and camelCase attributes, etc.
2. Update templates that rely on the project model.

**Comment by allthesignals** [comment]
## Back End
  - [ ] Enforce naming consistency in SQL query & JSON munging
  - [ ] Serve properties as camelCase key names

 ## Front End
 - [ ] Ensure naming consistency across models
 - [ ] Ensure consistency across the templates and that correct properties are being referenced
