### ISSUE TITLE
ZAP-API returns user-specific projects and side-loads attributes specific to user

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/deprecated-labs-zap-api#189]
Related: https://app.zenhub.com/workspaces/zap-search-5ca2355cd9fcf5278d715938/issues/nycplanning/labs-zap-search/550

**Comment by allthesignals** [comment]
@godfreyyeung going to expand this issue to include user-specific projects — can you tell me what attributes you meant in the previous title?

**Comment by allthesignals** [comment]
You mean user-specific resources, like dispositions?
