### ISSUE TITLE
For a Project  card on To Review, disable "Submit Recc" btn if not all hearings have been scheduled.

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/deprecated-labs-zap-api#190]
Disable button if any of the hearing records are blank.

**Comment by hannahkates** [comment]
We should hold off on this until we get clarity on the validation that's needed. See https://github.com/NYCPlanning/labs-zap-search/issues/707

**Comment by hannahkates** [comment]
Closing, no longer relevant
