### ISSUE TITLE
Consolidate all these milestone ids into constants

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/deprecated-labs-zap-api#199]
Is it possible to consolidate all these hardcoded milestone ids into constants for readability and easier future maintenance?

_Originally posted by @godfreyyeung in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDMyNDgyNzUyOQ==/comments/review_comment_

**Comment by hannahkates** [comment]
Probably done
