### ISSUE TITLE
Send disposition status upon submission

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/deprecated-labs-zap-api#229]
- [ ] When the LUP submits or opts out of their hearing, the statuscode should be changed to "Saved"
- [ ] When the LUP submits their recommendation, the statuscode should be changed to "Submitted"

**Comment by hannahkates** [comment]
Will confirm if this is necessary after testing team tests.

**Comment by hannahkates** [comment]
Confirmed, CRM isn't automatically updating this field. We need to send the status updates to CRM. These are likely enum options similar to other drop down value option sets.

**Comment by allthesignals** [comment]
https://dcppfsuat2.crm9.dynamics.com/api/data/v9.1/EntityDefinitions(LogicalName='dcp_communityboarddisposition')/Attributes(ad7b607f-a9c8-47cb-9763-6917ce44512e)/Microsoft.Dynamics.CRM.StatusAttributeMetadata?$select=LogicalName&$expand=OptionSet($select=Options),GlobalOptionSet($select=Options)

Options for statuscode

**Comment by allthesignals** [comment]
What did we decide is the definition of "opt out"? And submitting recommendation means a certain number of fields were filled out for each rec?

**Comment by allthesignals** [comment]
https://dcppfsuat2.crm9.dynamics.com/api/data/v9.1/EntityDefinitions(LogicalName='dcp_communityboarddisposition')/Attributes(dfbf8336-7e6b-43e2-b15c-b16b8b1c396f)/Microsoft.Dynamics.CRM.PicklistAttributeMetadata?$select=LogicalName&$expand=OptionSet($select=Options),GlobalOptionSet($select=Options)

ispublichearingrequired has a picklist type

**Comment by allthesignals** [comment]
Getting this error when posting: '2 is not a valid status code for state code dcp_communityboarddispositionState.Active on dcp_communityboarddisposition with Id 916d49fc-cef9-e911-a9b9-001dd8308fb0.'
