### ISSUE TITLE
Duplicate assignments provided in API response

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/deprecated-labs-zap-api#239]
There are duplicate assignments being provided in the API response.

This was spot checked by there being many multiple duplicate assignment IDs.

We should see if something is going wrong with one of the joins.

**Comment by hannahkates** [comment]
This seems to occur when an LUP user is assigned to one project with the same role multiple times in CRM. I'm working on a SQL fix for the API that deduplicates the response when that happens.
