### ISSUE TITLE
Add date recency check for `new-filed` route

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/deprecated-labs-zap-api#78]
There are ~1800 projects that don't have BBL matches in MapPLUTO that keep getting picked up in our query for filed projects. This means we are wasting processing power on attempting to reprocess them all the time. We should add some kind of date parameter that will limit which we process.

**Comment by hannahkates** [comment]
Should be resolved by https://github.com/NYCPlanning/labs-zap-api/pull/150

**Comment by allthesignals** [comment]
@hannahkates did you mean to link this issue? This issue is resolved by itself? :P

**Comment by hannahkates** [comment]
Haha yes @allthesignals, pasted wrong link. Updating now to https://github.com/NYCPlanning/labs-zap-api/pull/150.
